const menu = [
  {
    id: 1,
    title: "buttermilk pancakes",
    category: "breakfast",
    price: 15.99,
    img: "https://media.istockphoto.com/photos/breakfast-with-bacon-eggs-pancakes-and-toast-picture-id533645537?k=20&m=533645537&s=612x612&w=0&h=KJXCpAo9XQvMI_djcnRMSsz_Y7OGS6z3-8VThxWyR0Q=",
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 2,
    title: "diner double",
    category: "lunch",
    price: 13.99,
    img: "https://images.pexels.com/photos/958545/pexels-photo-958545.jpeg?cs=srgb&dl=pexels-chan-walrus-958545.jpg&fm=jpg",
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 3,
    title: "Chocolate PB&J shake",
    category: "shakes",
    price: 6.99,
    img: "https://media-cldnry.s-nbcnews.com/image/upload/newscms/2019_27/1456097/sunny-anderson-shake-today-190704-square-01.jpg",
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
  },
  {
    id: 4,
    title: "Tea or paratha",
    category: "breakfast",
    price: 20.99,
    img: "https://tribune-reloaded.s3.amazonaws.com/media/images/1100455-breaky-1462866009/1100455-breaky-1462866009.png",
    desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
  },
  {
    id: 5,
    title: "egg attack",
    category: "lunch",
    price: 22.99,
    img: "https://media.istockphoto.com/photos/assorted-indian-non-vegetarian-food-recipe-served-in-a-group-includes-picture-id1169694902?k=20&m=1169694902&s=612x612&w=0&h=fcipoyPcRtCEK3rsFiSbU8Tt7Tj5lm-VsxyvVXHCfL4=",
    desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
  },
  {
    id: 6,
    title: "Milk shake",
    category: "shakes",
    price: 18.99,
    img: "https://images.unsplash.com/photo-1571328003758-4a3921661729?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8OXx8bWlsayUyMHNoYWtlfGVufDB8fDB8fA%3D%3D&w=1000&q=80",
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
  },
  {
    id: 7,
    title: "Halwa Puri",
    category: "breakfast",
    price: 8.99,
    img: "https://en.dailypakistan.com.pk/digital_images/large/2018-08-05/halwa-puri-most-favourite-breakfast-for-punjabi-families-on-sunday-1572332421-9333.jpg",
    desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
  },
  {
    id: 8,
    title: "Hamburger",
    category: "lunch",
    price: 12.99,
    img: "https://i.pinimg.com/originals/8e/7d/2b/8e7d2be426eb66b702312774f68c7e15.jpg",
    desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
  },
  {
    id: 9,
    title: "Dry fruit milk shake",
    category: "shakes",
    price: 16.99,
    img: "https://www.indianhealthyrecipes.com/wp-content/uploads/2018/07/dry-fruits-milkshake.jpg",
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
];
export default menu;
